import type { CollectionData } from '../types'
import { createId } from './id'

export function createDemoCollection(): CollectionData {
  const now = new Date().toISOString()

  return {
    version: 1,
    profile: {
      ownerName: 'mika',
      bio: 'A display cabinet for my badges, figures, and anime merchandise.',
    },
    rooms: [
      {
        id: 'demo-room-1',
        name: 'Satoru Gojo Collection',
        description: 'Badges, acrylic stands, and cards featuring Satoru Gojo.',
        accent: 'blue',
        isPublic: true,
      },
      {
        id: 'demo-room-2',
        name: 'Desktop Figure Cabinet',
        description: 'Figures and models that look great on a desk.',
        accent: 'gold',
        isPublic: false,
      },
    ],
    items: [
      {
        id: createId(),
        roomId: 'demo-room-1',
        isPublic: true,
        name: 'Satoru Gojo Mirror Badge',
        category: 'badge',
        series: 'Jujutsu Kaisen',
        character: 'Satoru Gojo',
        rarity: 'common',
        purchasePrice: 0,
        referencePrice: 68,
        purchaseDate: now.slice(0, 10),
        condition: 'near_mint',
        notes: 'A perfect centerpiece for an ita bag. The silver reflection looks great under display lighting.',
        imageDataUrl: null,
        virtualFigureStatus: 'none',
        virtualFigureModelUrl: null,
        virtualFigureProvider: null,
        virtualFigureJobId: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: createId(),
        roomId: 'demo-room-1',
        isPublic: true,
        name: 'Hatsune Miku Anniversary Stand',
        category: 'acrylic',
        series: 'Hatsune Miku',
        character: 'Hatsune Miku',
        rarity: 'common',
        purchasePrice: 0,
        referencePrice: 120,
        purchaseDate: now.slice(0, 10),
        condition: 'near_mint',
        notes: 'The bright teal colors pair beautifully with cards from the same series.',
        imageDataUrl: null,
        virtualFigureStatus: 'none',
        virtualFigureModelUrl: null,
        virtualFigureProvider: null,
        virtualFigureJobId: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: createId(),
        roomId: 'demo-room-2',
        isPublic: false,
        name: '1/7 Scale Figure',
        category: 'figure',
        series: 'Original Character',
        character: 'Mascot Character',
        rarity: 'common',
        purchasePrice: 0,
        referencePrice: 980,
        purchaseDate: now.slice(0, 10),
        condition: 'near_mint',
        notes: 'The best centerpiece in the collection right now.',
        imageDataUrl: null,
        virtualFigureStatus: 'none',
        virtualFigureModelUrl: null,
        virtualFigureProvider: null,
        virtualFigureJobId: null,
        createdAt: now,
        updatedAt: now,
      },
    ],
  }
}
